### ISSUE TITLE
Failed to pull images

### ISSUE THREAD

**Issue by daxmc99** [BuoyantIO/emojivoto#101]
`docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11` are not currently pullable

**Comment by olix0r** [comment]
Thanks @daxmc99.

We tried moving these images to a custom domain, but it appears that containerd has a bug following redirects (one of these https://github.com/containerd/containerd/issues?q=is%3Aissue+is%3Aopen+401+ -- not sure which one, exactly).

Note that you can probably pull these images in docker without issue:

```
:; docker pull docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
v11: Pulling from buoyantio/emojivoto-voting-svc
Digest: sha256:a57ac67af7a5b05988a38b49568eca6a078ef27a71c148c44c9db4efb1dac58b
Status: Image is up to date for docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
```

If we can't sort this out in the next few days I'll revert the change, but for now you can work around it with:
```
:; curl -sL https://run.linkerd.io/emojivoto.yml | sed -e 's/docker.l5d.io/docker.io/'
```

**Comment by daxmc99** [comment]
Thanks! I was confused why I could pull them locally but not in a GKE cluster with containerd nodes. 
I'll leave this open for now

**Comment by olix0r** [comment]
@daxmc99 I think this has been fixed. Can you confirm?

**Comment by scottcarol** [comment]
I was having the same problem yesterday and it is fixed for me now, thanks! 🥳

**Comment by daxmc99** [comment]
This appears to be fixed for me as well! Thanks! 🎉
