### ISSUE TITLE
the log of emojivoto-web

### ISSUE THREAD

**Issue by sysuKinthon** [BuoyantIO/emojivoto#78]
I use docker-compose to deploy the applications, and got some log which seem a little strange. 
>voting-svc_1  | 2019/10/26 08:41:15 Starting grpc server on GRPC_PORT=[8080]
emoji-svc_1   | 2019/10/26 08:41:15 Starting grpc server on GRPC_PORT=[8080]
web_1         | 2019/10/26 08:41:16 Connecting to [voting-svc:8080]
web_1         | 2019/10/26 08:41:16 Connecting to [emoji-svc:8080]
web_1         | 2019/10/26 08:41:16 Starting web server on WEB_PORT=[8080]
voting-svc_1  | 2019/10/26 08:42:55 Voted for [:interrobang:], which now has a total of [1] votes
web_1         | 2019/10/26 08:42:56 Error serving request [&{GET /api/vote?choice=:doughnut: HTTP/1.1 1 1 map[User-Agent:[Go-http-client/1.1] Accept-Encoding:[gzip]] {} <nil> 0 [] false localhost:8089 map[choice:[:doughnut:]] map[] <nil> map[] 172.19.0.1:33281 /api/vote?choice=:doughnut: <nil> <nil> <nil> 0xc0002858c0}]: rpc error: code = Unknown desc = ERROR
voting-svc_1  | 2019/10/26 08:42:57 Voted for [:poop:], which now has a total of [1] votes
voting-svc_1  | 2019/10/26 08:42:58 Voted for [:dancer:], which now has a total of [1] votes

I got an error message of web_1. 

The docker-compose
> version: '3'
services:
  web:
    image: buoyantio/emojivoto-web:v8
    environment:
      - WEB_PORT=8080
      - EMOJISVC_HOST=emoji-svc:8080
      - VOTINGSVC_HOST=voting-svc:8080
      - INDEX_BUNDLE=dist/index_bundle.js
    ports:
      - "8080:8080"
    depends_on:
      - voting-svc
      - emoji-svc
  emoji-svc:
    image: buoyantio/emojivoto-emoji-svc:v8
    environment:
      - GRPC_PORT=8080
    ports:
      - "8081:8080"
  voting-svc:
    image: buoyantio/emojivoto-voting-svc:v8
    environment:
      - GRPC_PORT=8080
    ports:
      - "8082:8080"

I use `go run main.go` to  run the emojivoto-vote-bot.

----

I also deploy the application to k8s, and got an error of web-svc,
> 2019/10/25 07:09:47 Connecting to [voting-svc-2.emojivoto:8080]
2019/10/25 07:09:47 Connecting to [emoji-svc-2.emojivoto:8080]
2019/10/25 07:09:47 Starting web server on WEB_PORT=[8080]
2019/10/25 07:10:08 Error serving request [&{GET /api/list HTTP/1.1 1 1 map[] {} <nil> 0 [] false web-svc-2.emojivoto.svc.cluster.local:8080 map[] map[] <nil> map[] 172.16.60.3:58724 /api/list <nil> <nil> <nil> 0xc00023ff80}]: rpc error: code = Canceled desc = context canceled
2019/10/25 07:10:08 Error serving request [&{GET /api/list HTTP/1.1 1 1 map[] {} <nil> 0 [] false web-svc-2.emojivoto.svc.cluster.local:8080 map[] map[] <nil> map[] 172.16.60.3:58742 /api/list <nil> <nil> <nil> 0xc000360040}]: rpc error: code = Canceled desc = context canceled.

What do the error means?

**Comment by klingerf** [comment]
Hi @sysuKinthon, this error is expected:

> web_1 | 2019/10/26 08:42:56 Error serving request [&{GET /api/vote?choice=🍩 HTTP/1.1 1 1 map[User-Agent:[Go-http-client/1.1] Accept-Encoding:[gzip]] {} 0 [] false localhost:8089 map[choice:[🍩]] map[] map[] 172.19.0.1:33281 /api/vote?choice=🍩 0xc0002858c0}]: rpc error: code = Unknown desc = ERROR

The app is configured to always return an error when somebody votes for the 🍩 emoji. If you load the web UI and try to vote for 🍩 , you see:

![image](https://user-images.githubusercontent.com/9226/67698769-33a6df80-f968-11e9-8cd4-e3753c23c2da.png)

This is intentional, to show of Linkerd's observability features. For more info, see the [getting started guide](https://linkerd.io/2/getting-started).

**Comment by sysuKinthon** [comment]
Thanks a lot. 
>2019/10/25 07:10:08 Error serving request [&{GET /api/list HTTP/1.1 1 1 map[] {} 0 [] false web-svc-2.emojivoto.svc.cluster.local:8080 map[] map[] map[] 172.16.60.3:58724 /api/list 0xc00023ff80}]: rpc error: code = Canceled desc = context canceled

Is this error of web-svc also expected?
